version: '3'
services:
  config:
    hostname: config
    image: springfivebyexample/config
    ports:
      - "5000:5000"
    networks:
      - airline
  rabbitmq:
    hostname: rabbitmq
    image: rabbitmq:3.7.0-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - airline
  mysql:
    hostname: mysql
    image: mysql:5.7.21
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=zipkin
    networks:
      - airline
  discovery:
    hostname: discovery
    image: springfivebyexample/discovery
    ports:
      - "8761:8761"
    networks:
      - airline
  gateway:
    hostname: gateway
    image: springfivebyexample/gateway
    ports:
      - "8888:8888"
    networks:
      - airline
  zipkin:
    hostname: zipkin
    image: springfivebyexample/zipkin
    ports:
      - "9999:9999"
    networks:
      - airline
networks:
  airline:
    driver: bridge